travis:
  secure:
    BINSTAR_TOKEN: OEOS36a7Dt5NRWwiv2WjD3brSz7dn6ustAlp0xYrVvdt9HaumHuxXK0ab+NSJCibrr5WMva/gAJ7V3gPV+fVPirTWb3wtlnom+x6de9CV5fEBftrfk8bq72R4Zc9i4QgRB7ObDD3XAXpRZ62yrL+XNDIT16w07WswMSsom5WbxSB2p6HDQ2f78FIwX3mHeVpREl3dTxG0E7i7WAuOTEbcsGHEHvXcoa8NipFJBrpA/rBqjydjKfI88wTiGe3c3VM99oUL4RFKOV00IEHAv3UMKZjRtdO+B3d4HXgpFrwxzPRRLF4N0vZIq/88Mi3WTLtjGyRNpgVKaSMCeegDMTbsOKG2XnAP8rpR2x1qXJ2RYoNJunjXLBVg4j2N/rV2whcwyqsfvURqgfmSOe9WLaXuHN94eI3g3UefJ4rwSvmdvt2efUryKrMrJBGZKyWp6OR8Uqdxiz/SJVQK0gou2dps+pEF3rKV4Sg6J79+Nxbifd3+mR8J1BzwqUrP6wWKY6qsgg++jZCNPgH7Ke7UKfl7xM9yfpVqKU4aHo7T5j+Xl2p5CoBvxEzRhasCLePhuXlsJv7C9VOsgDnwaqJCKNBfNEyPt9FveG8l8zMtqiJ85gN/7XQnyjtRX1VUnWA6M59lcHxdjy9xnhJdSQZb33B+pGZMems+NFlxiDI0InkoGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
