travis:
  secure:
    BINSTAR_TOKEN: LixLykiRg7LMiXwelgc5MUf8JR5oLmBK9XDy2M3NVCLjUBRsvMQfZ5Cmu7vKfsuRx8aO6Kli9mV+HY8W/cgnrxSmU0ZwMU84SxV8gBRCs79W6yN7JVUVq0557qQ9KTD2SZwwQQkJLMHNe20/yl+y3JBVw0DTWA61fbS9fJVeiu1jqqTKsS9EwG9uZNw+586vAbhC4wrcHJc/R/IqoJ0Pa8jUUS3KZ2tTWJKTx4UWl6R5iz83VQ3di+4cmIweFyvUEpRdz9Wep8aTbkVSwZFdXJC3K5MFF21yq63wsXgaF85g67VJZacHPpo0J7dCh85QljqCxe5H/HrudDmZYDgwwWZ/89IA3ETRSN+1c2L1G/adH4Qx2FZSOF7Kl9ht8lqPpsI6a9zSAEa7Vp2TCnxYaix1ltYI7uJ7iB/nKNAEOIS3eESEtVQ2jtY4rrkU8gbePNjX9g3PKpl9gtUmv6+FpqyH9IBdG49//Tc29DOBNxkpudpsbFQxFEqUA9kuFGjNb64Ul4GqK6hY335ESsFE5CRSO91TsdZMVQczYrjII9kfdhdJxzTWdLJMwC4YJx/oijTe1uPKmXs7irfXoxDepmgm9cTzVYa3QOpUwOlXbh8U7tv2V+J5rsDCc5pKsOUad3ZPUwAJj8XJfKAi8vu6wngMYek9NhSG+4sPjD5iQ6E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
